### PR TITLE
Look up connection implementation by class name

### PR DESCRIPTION
**Pull request by charlieschwabacher**
This prevents needing to restart a rails server each time `items_class` is modified / autoloaded as a new object.

### CODE REVIEW

**Comment by rmosolgo** [comment]
Do you have a custom connection class too? How does that play with autoloading? 

(I've been working on a custom connection too, but it's part of a gem, so I haven't interacted with Rails autoloading in that context!)

**Comment by charlieschwabacher** [comment]
Hey - yeah, should have mentioned this only comes up w/ a custom connection class.  If you modify a model that is using the standard RelationConnection, the model class is reloaded, but it is checked against ActiveRecord::Relation which is unchanged, so it is still able to match it to the connection.

In my case, I have done:

```
class MyQueryClass
end

class MyConnectionImplementation < GraphQL::Relay::BaseConnection
  GraphQL::Relay::BaseConnection.register_connection_implementation(
    MyQueryClass,
    MyConnectionImplementation
  )
end
```

W/ a setup like this, any time I modify the file for my query class, rails auto-loads a new version of that class, but the old version stays registered w/ Relay::BaseConnection.  Instances of the new version no longer return true for `is_a?` the old version, so you end up with "No connection implementation to wrap #{items.class} (#{items})" errors and need to restart the rails server.

**Comment by charlieschwabacher** [comment]
@rmosolgo how are you thinking about this pull? - are you concerned about performance of string comparison vs `is_a?` - it could potentially do something like check `defined? Rails` and `Rails.env.development?`

**Comment by rmosolgo** [comment]
Sorry, it just slipped my radar! 

I'm hemming and hawing because it just doesn't feel right to refactor it _just_ for Rails development. I haven't run into this myself because my custom collection & connection classes are in gem code, not app code, so it's never reloaded.

The only workaround I can think of is putting the `register_connection_implementation` code in _both_ files (presumably both of them are under development). Or putting it in some helper method and calling the helper method at the bottom of both files. 

Those just aren't ideal, either! 

Since there's no good way to test this behavior, could you add a brief explanatory comment in the code? I can imagine accidentally "simplifying" it (and breaking it)

**Comment by charlieschwabacher** [comment]
Hey - added the comment.  I agree - adding a workaround for Rails here doesn't feel great.  The only clean feeling way I can think of to fix this is for Rails to keep track of replaced classes and patch `is_a?` to check against the history, although I would bet that just digs the hole deeper in some other way :confounded:

Anyways, I guess I lean towards including the workaround here because I imagine some big fraction of use will be alongside rails, but I would not be offended at all if you close this in favor of `register_connection_implementation` in the file for the items class.

**Comment by rmosolgo** [comment]
:moneybag: thanks, looks great!

**Comment by rmosolgo** [comment]
Shipped in 0.6.2

**Pull request merged**
